<?php

namespace app\components;

use yii\bootstrap5\Html;
use yii\db\BaseActiveRecord;

class ActiveField extends \yii\bootstrap5\ActiveField
{
    /**
     * {@inheritdoc}
     */
    public $inputOptions = ['class' => ['widget' => 'form-control form-control-sm']];
    
    protected function getInputId()
    {
        $name = Html::getInputName($this->model, $this->attribute);
        if ($this->model instanceof BaseActiveRecord) {
            $name = sprintf('%s_%d', Html::getInputIdByName($name), $this->model->primaryKey);
        } else {
            $name = parent::getInputId();
        }
        return $name;
    }
    
    public function checkbox($options = [], $enclosedByLabel = false)
    {
        $options['id'] = $this->getInputId();
        return parent::checkbox($options, $enclosedByLabel); // TODO: Change the autogenerated stub
    }
    
    public function radio($options = [], $enclosedByLabel = false)
    {
        $options['id'] = $this->getInputId();
        return parent::radio($options, $enclosedByLabel); // TODO: Change the autogenerated stub
    }
    
    public function fileInput($options = [])
    {
        $options['id'] = $this->getInputId();
        return parent::fileInput($options); // TODO: Change the autogenerated stub
    }
    
    public function textInput($options = [])
    {
        $options['id'] = $this->getInputId();
        return parent::textInput($options); // TODO: Change the autogenerated stub
    }
    
    public function hiddenInput($options = [])
    {
        $options['id'] = $this->getInputId();
        return parent::hiddenInput($options); // TODO: Change the autogenerated stub
    }
    
    public function textarea($options = [])
    {
        $options['id'] = $this->getInputId();
        return parent::textarea($options); // TODO: Change the autogenerated stub
    }
    
}
